-- 코드를 입력하세요
SELECT R.USER_ID, R.NICKNAME, 
CONCAT_WS(' ', R.CITY, R.STREET_ADDRESS1, R.STREET_ADDRESS2) AS 전체주소, 
CONCAT_WS('-', SUBSTR(R.TLNO, 1,3), SUBSTR(R.TLNO, 4,4), SUBSTR(R.TLNO, 8,4)) AS 전화번호
FROM USED_GOODS_BOARD D JOIN USED_GOODS_USER R ON D.WRITER_ID = R.USER_ID
GROUP BY R.USER_ID
HAVING COUNT(R.USER_ID) >= 3
ORDER BY R.USER_ID DESC;