-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', E.BOARD_ID, '/', E.FILE_ID, E.FILE_NAME, E.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD D JOIN USED_GOODS_FILE E ON D.BOARD_ID = E.BOARD_ID
WHERE D.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC;